image: python:3
lint:
 stage: test
 script:
 - pip install yapf
 - yapf --recursive . --diff --style google
 only:
 - merge_requests
 
unittest:
 stage: test
 script: 
 - pip install -r requirements.txt
 - pytest
 only:
 - pushes
 